VetrovShop.WEB/Controllers/HomeController.cs
using System;
using System.Xml.Serialization;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace TaskTwo.Controllers
{
 
    public class HomeController : Controller
    {
        [Authorize]
        public IActionResult Index()
        {
            System.Diagnostics.Debug.WriteLine(User.Identity.IsAuthenticated);
            return View();
        }

        //public IActionResult Serialization()
        //{
        //    return View();
        //}
        
        //[HttpPost]
        //public IActionResult Serialization(Product product)
        //{
        //    try
        //    {
        //        string fileName = Server.MapPath(".").ToString() + @"\..\product.xml";
        //        Directory.CreateDirectory(Path.GetDirectoryName(fileName));

        //        XmlSerializer formatter = new XmlSerializer(typeof(Product));

        //        using (FileStream fs = new FileStream(fileName, FileMode.OpenOrCreate))
        //        {
        //            formatter.Serialize(fs, product);
        //        }

        //        ViewBag.Status = "Done";
        //        return View();
        //    }
        //    catch (Exception ex)
        //    {
        //        ViewBag.Error = ex.Message;
        //        return View("Error");
        //    }
        //}

        //public IActionResult ShowXml()
        //{
        //    try
        //    {
        //        Product product = new Product();

        //        string fileName = Server.MapPath(".").ToString() + @"\..\product.xml";
        //        Directory.CreateDirectory(Path.GetDirectoryName(fileName));

        //        XmlSerializer formatter = new XmlSerializer(typeof(Product));

        //        using (FileStream fs = new FileStream(fileName, FileMode.OpenOrCreate))
        //        {
        //            product = (Product)formatter.Deserialize(fs);
        //        }

        //        return View("ShowXmlPartial", product);
        //    }
        //    catch (Exception ex)
        //    {
        //        ViewBag.Error = ex.Message;
        //        return View("Error");
        //    }
        //}
    }
}

VetrovShop.WEB/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using VetrovShop.Services.Interfaces;
using VetrovShop.Models;
using System.Security.Claims;
using VetrovShop.WEB.ViewModels;
using System.Net.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace VetrovShop.WEB.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private IOrderService orderService;
        private IProductService productService;
        private UserManager<User> _UserManager;

        public OrderController(IOrderService orderService, IProductService productService, UserManager<User> _UserManager)
        {
            this.orderService = orderService;
            this.productService = productService;
            this._UserManager = _UserManager;
        }

        public IActionResult Index()
        {
            string userid = User.FindFirstValue(ClaimTypes.NameIdentifier);
            List<OrderInfo> orderinfo = orderService.OrderInfo(userid); 
            return View(orderinfo);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewData["products"] = productService.GetAll();
            return View();
        }

        [HttpPost]
        public IActionResult CreateOrder()
        {
            string str = HttpContext.Request.Form["checkProduct"].ToString();
            string userid = User.FindFirstValue(ClaimTypes.NameIdentifier);


            int[] productId = str.Split(',').Select(t => Convert.ToInt32(t)).ToArray();

            Order order = new Order {
                DatePurchase = new DateTime(),
                UserId = userid
            };

            for (int i = 0; i < productId.Length; ++i)
            {
                var id = productId[i];
                ProductOrder po = new ProductOrder();
                po.ProductId = productId[i];
                order.ProductOrders.Add(po);
            }

            orderService.CreateOrder(order);
            return RedirectToAction("Index");
        }
    }
}

VetrovShop.WEB/Controllers/RolesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using VetrovShop.DAL.Identity;
using VetrovShop.Models;

namespace VetrovShop.WEB.Controllers
{
    [Authorize(Roles = "Superuser")]
    public class RolesController : Controller
    {

        private RoleManager<IdentityRole> _RoleManager;
        private UserManager<User> _UserManager;

        public RolesController(RoleManager<IdentityRole> _RoleManager, UserManager<User> _UserManager)
        {
            this._RoleManager = _RoleManager;
            this._UserManager = _UserManager;
        }

        public IActionResult Index() => View(_RoleManager.Roles.ToList());

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _RoleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _RoleManager.FindByIdAsync(id);

            if (role.Name == RoleInitializer.GetSuperRole)
                return RedirectToAction("Index");

            if (role != null)
            {
                IdentityResult result = await _RoleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_UserManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            User user = await _UserManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _UserManager.GetRolesAsync(user);
                var allRoles = _RoleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            User user = await _UserManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _UserManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _RoleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _UserManager.AddToRolesAsync(user, addedRoles);

                await _UserManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

VetrovShop.WEB/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using VetrovShop.Models;

namespace VetrovShop.WEB.Controllers
{
    public class UserController : Controller
    {
        private UserManager<User> _UserManager;

        public UserController(UserManager<User> _UserManager)
        {
            this._UserManager = _UserManager;
        }

        public async Task<IActionResult> Index()
        {
            var user = await _UserManager.GetUserAsync(User);
            return View(user);
        }
    }
}

VetrovShop.WEB/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

VetrovShop.WEB/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

VetrovShop.WEB/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-lg-4" id="ref">
        <h2>@Html.ActionLink("Products", "Index", "Product")</h2>
    </div>
    <div class="col-lg-4" id="ref">
        <h2>@Html.ActionLink("Orders", "Index", "Order")</h2>
    </div>
    <div class="col-lg-4" id="ref">
        <h2>@Html.ActionLink("My Account", "Index", "User")</h2>
    </div>
    @{
        if (User.IsInRole("Superuser"))
        {
            <div class="col-lg-4" id="ref">
                <h2>@Html.ActionLink("Manage users", "Index", "Roles")</h2>
            </div>
        }
    }


</div>

VetrovShop.WEB/Views/Home/Serialization.cshtml
@*@model TaskTwo.Models.Product

@{
    ViewBag.Title = "Serialization";
}

<h2>Serialization</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Describe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Describe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Describe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Serialize" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@Html.Action("ShowXml", "Home")


<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

VetrovShop.WEB/Views/Home/ShowXmlPartial.cshtml
@*@model TaskTwo.Models.Product

@{
    Layout = null;
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Describe)
        </th>
        <th></th>
    </tr>
    <tr>
        <td>
            @Html.DisplayFor(model => model.ProductName)
        </td>
        <td>
            @Html.DisplayFor(model => model.Price)
        </td>
        <td>
            @Html.DisplayFor(model => model.Describe)
        </td>
    </tr>
</table>*@